// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// cart.go
type Cart struct {
    CartID     uint      `gorm:"primaryKey" json:"cart_id"`
    CustomerID uint      `gorm:"not null" json:"customer_id"`
    CartName   string    `gorm:"not null" json:"cart_name"`
    CreatedAt  time.Time `json:"created_at"`
    UpdatedAt  time.Time `json:"updated_at"`
    
    Customer   Customer   `gorm:"foreignKey:CustomerID" json:"-"`
    CartItems  []CartItem `gorm:"foreignKey:CartID" json:"cart_items"`
}

func (m *Cart) TableName() string {
	return "cart"
}

