// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Product struct {
    ProductID     uint      `gorm:"primaryKey" json:"product_id"`
    ProductName   string    `gorm:"not null" json:"product_name"`
    Description   string    `json:"description"`
    Price         float64   `gorm:"not null" json:"price"`
    StockQuantity int       `gorm:"not null" json:"stock_quantity"`
    CreatedAt     time.Time `json:"created_at"`
    UpdatedAt     time.Time `json:"updated_at"`
}

func (m *Product) TableName() string {
	return "product"
}

